// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9wO4iotFzZfzNTGpdpq3KKZW49OXIinU',
    appId: '1:570395077653:web:82fe7a365949b1043bb21c',
    messagingSenderId: '570395077653',
    projectId: 'blood-app-8f4c2',
    authDomain: 'blood-app-8f4c2.firebaseapp.com',
    storageBucket: 'blood-app-8f4c2.appspot.com',
    measurementId: 'G-W109M8NMCG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWLAUGNzpQcKlnmSoZKtdSbZEz2lYHrKs',
    appId: '1:570395077653:android:011a7bd5d6618f8a3bb21c',
    messagingSenderId: '570395077653',
    projectId: 'blood-app-8f4c2',
    storageBucket: 'blood-app-8f4c2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGTdqR6ecyJyCpmF08F6y2FkpucF6ewwI',
    appId: '1:570395077653:ios:666045385249fce43bb21c',
    messagingSenderId: '570395077653',
    projectId: 'blood-app-8f4c2',
    storageBucket: 'blood-app-8f4c2.appspot.com',
    iosBundleId: 'com.example.bloodDonor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGTdqR6ecyJyCpmF08F6y2FkpucF6ewwI',
    appId: '1:570395077653:ios:33097cf92e9bc9ec3bb21c',
    messagingSenderId: '570395077653',
    projectId: 'blood-app-8f4c2',
    storageBucket: 'blood-app-8f4c2.appspot.com',
    iosBundleId: 'com.example.bloodDonor.RunnerTests',
  );
}
